name = "fast-api"
compatibility_date = "2024-09-02"

[vars]
UPSTASH_REDIS_REST_TOKEN = "AbupAAIjcDFmNTc0YjVmZDQwOTE0ZTc1YWU3OGY5NjljNWRlMDRiOHAxMA"
UPSTASH_REDIS_REST_URL = "https://mighty-garfish-48041.upstash.io"